export const SEMICIRCLE_COUNT_TOGGLE_KEY = "semicircleCountCyclerEnabled";

export const eventTypes = {
  "Tornado Warning": "tornado-warning",
  "Radar Confirmed Tornado Warning": "observed-tornado-warning",
  "Spotter Confirmed Tornado Warning": "observed-tornado-warning",
  "Emergency Mgmt Confirmed Tornado Warning": "observed-tornado-warning",
  "Law Enforcement Confirmed Tornado Warning": "observed-tornado-warning",
  "Public Confirmed Tornado Warning": "observed-tornado-warning",
  "Observed Tornado Warning": "observed-tornado-warning",
  "PDS Tornado Warning": "pds-tornado-warning",
  "Tornado Emergency": "tornado-emergency",
  "Severe Thunderstorm Warning": "severe-thunderstorm-warning",
  "Considerable Severe Thunderstorm Warning":
    "severe-thunderstorm-considerable",
  "Destructive Severe Thunderstorm Warning": "pds-severe-thunderstorm-warning",
  "Flash Flood Warning": "flash-flood-warning",
  "Considerable Flash Flood Warning": "considerable-flash-flood-warning",
  "Flash Flood Emergency": "flash-flood-emergency",
  "Flood Warning": "flood-warning",
  "Flood Advisory": "flood-advisory",
  "Flood Watch": "flood-watch",
  "Tornado Watch": "tornado-watch",
  "Severe Thunderstorm Watch": "severe-thunderstorm-watch",
  "Winter Weather Advisory": "winter-weather-advisory",
  "Winter Storm Watch": "winter-storm-watch",
  "Winter Storm Warning": "winter-storm-warning",
  "Special Weather Statement": "special-weather-statement",
  "Ice Storm Warning": "ice-storm-warning",
  "Blizzard Warning": "blizzard-warning",
  "High Wind Warning": "high-wind-warning",
  "High Wind Watch": "high-wind-watch",
  "Wind Advisory": "wind-advisory",
  "Dense Fog Advisory": "dense-fog-advisory",
  "Snow Squall Warning": "snow-squall-warning",
  "Extreme Heat Warning": "extreme-heat-warning",
  "Extreme Heat Watch": "extreme-heat-watch",
  "Heat Advisory": "heat-advisory",
  "Frost Advisory": "frost-advisory",
  "Freeze Watch": "freeze-watch",
  "Freeze Warning": "freeze-warning",
  "Cold Weather Advisory": "cold-weather-advisory",
  "Wind Chill Warning": "wind-chill-warning",
  "Extreme Cold Warning": "extreme-cold-warning",
  "Extreme Cold Watch": "extreme-cold-watch",
  "Lake Effect Snow Warning": "lake-effect-snow-warning",
};

export const priority = {
  "Tornado Emergency": 1,
  "PDS Tornado Warning": 2,
  "Observed Tornado Warning": 3,
  "Emergency Mgmt Confirmed Tornado Warning": 4,
  "Spotter Confirmed Tornado Warning": 5,
  "Law Enforcement Confirmed Tornado Warning": 6,
  "Public Confirmed Tornado Warning": 7,
  "Radar Confirmed Tornado Warning": 8,
  "Tornado Warning": 9,
  "Destructive Severe Thunderstorm Warning": 10,
  "Considerable Severe Thunderstorm Warning": 11,
  "Severe Thunderstorm Warning": 12,
  "Flash Flood Emergency": 13,
  "Considerable Flash Flood Warning": 14,
  "Flash Flood Warning": 15,
  "Tornado Watch": 16,
  "Severe Thunderstorm Watch": 17,
  "Blizzard Warning": 18,
  "Ice Storm Warning": 19,
  "Snow Squall Warning": 20,
  "Winter Storm Warning": 21,
  "Winter Weather Advisory": 22,
  "Winter Storm Watch": 23,
  "Lake Effect Snow Warning": 24,
  "Flood Warning": 25,
  "Flood Watch": 26,
  "Flood Advisory": 27,
  "Special Weather Statement": 28,
  "Wind Chill Warning": 29,
  "Extreme Cold Warning": 30,
  "Extreme Cold Watch": 31,
  "Cold Weather Advisory": 32,
  "High Wind Warning": 33,
  "High Wind Watch": 34,
  "Wind Advisory": 35,
  "Extreme Heat Warning": 36,
  "Extreme Heat Watch": 37,
  "Heat Advisory": 38,
  "Freeze Warning": 39,
  "Freeze Watch": 40,
  "Frost Advisory": 41,
  "Dense Fog Advisory": 42,
};

export const STATE_FIPS_TO_ABBR = {
  Any: "US",
  "01": "AL",
  "02": "AK",
  "04": "AZ",
  "05": "AR",
  "06": "CA",
  "08": "CO",
  "09": "CT",
  10: "DE",
  11: "DC",
  12: "FL",
  13: "GA",
  15: "HI",
  16: "ID",
  17: "IL",
  18: "IN",
  19: "IA",
  20: "KS",
  21: "KY",
  22: "LA",
  23: "ME",
  24: "MD",
  25: "MA",
  26: "MI",
  27: "MN",
  28: "MS",
  29: "MO",
  30: "MT",
  31: "NE",
  32: "NV",
  33: "NH",
  34: "NJ",
  35: "NM",
  36: "NY",
  37: "NC",
  38: "ND",
  39: "OH",
  40: "OK",
  41: "OR",
  42: "PA",
  44: "RI",
  45: "SC",
  46: "SD",
  47: "TN",
  48: "TX",
  49: "UT",
  50: "VT",
  51: "VA",
  53: "WA",
  54: "WV",
  55: "WI",
  56: "WY",
};

export const CITY_STATIONS = [
  { city: "Detroit", station: "KDTW" },
  { city: "Lansing", station: "KLAN" },
  { city: "Grand Rapids", station: "KGRR" },
  { city: "Kalamazoo", station: "KAZO" },
  { city: "Hillsdale", station: "KJYM" },
  { city: "Flint", station: "KFNT" },
  { city: "Bad Axe", station: "KBAX" },
  { city: "Mount Pleasant", station: "KMOP" },
  { city: "Ludington", station: "KLDM" },
  { city: "Cadillac", station: "KCAD" },
  { city: "Gaylord", station: "KGLR" },
  { city: "Houghton", station: "KCMX" },
  { city: "Marquette", station: "KSAW" },
  { city: "Sault Ste. Marie", station: "KANJ" },
];

export const riskLevels = [
  { name: "HIGH", class: "risk-HIGH", color: "#F918FF" },
  { name: "MODERATE", class: "risk-MOD", color: "#AD0200" },
  { name: "ENHANCED", class: "risk-ENH", color: "#ff9900" },
  { name: "SLIGHT", class: "risk-SLIGHT", color: "#ffff00" },
  { name: "MARGINAL", class: "risk-MARGINAL", color: "#00c000" },
  { name: "TSTM", class: "risk-TSTM", color: "#0085ff" },
];

export const WEATHER_ICONS = {
  clear: "https://i.imgur.com/jKEHIsy.png",
  cloudy: "https://i.imgur.com/AcihKAW.png",
  "partly-cloudy": "https://i.imgur.com/37bCqbo.png",
  rain: "https://i.imgur.com/yS8RtPE.png",
  snow: "https://i.imgur.com/yEu5fVZ.png",
  thunderstorm: "https://i.imgur.com/DG1Wz63.png",
  fog: "https://i.imgur.com/uwHDNIA.png",
};
